name: student_app
description: A new Flutter application.
publish_to: 'none'
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_cupertino_localizations: ^1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_offline: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  http: ^0.13.3
  mask_text_input_formatter: ^2.0.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - lang/en.json
    - lang/ar.json
    - assets/images/bg.png
    - assets/images/ff.png
    - assets/images/splash_bg.png
    - assets/images/intro_bg.png
    - assets/images/welcome_bg.png
    - assets/images/Rectangle.png
    - assets/images/home.png
    - assets/images/person.png
    - assets/images/logout.png
    - assets/images/bg.png
    - assets/images/logo.png
    - assets/images/intro_bg.png
    - assets/images/Rectangle.png
    - assets/images/home.png
    - assets/images/person.png
    - assets/images/logout.png
    - assets/images/menu.png
    - assets/images/educational_semesters.png
    - assets/images/educational_classes.png
    - assets/images/educational_materials.png
    - assets/images/teachers_info.png
    - assets/images/students_requests.png
    - assets/images/students_info.png
    - assets/images/icon_educational_classes.png
    - assets/images/icon_educational_material.png
    - assets/images/icon_teachers_info.png
    - assets/images/students_requests_icon.png
    - assets/images/students_info_icon.png
    - assets/images/reports.png
    - assets/images/review_lectures.png
    - assets/images/teacher.png
    - assets/images/back.png
    - assets/images/alrwad.jpg
    - assets/images/upload.png
    - assets/images/calendar.png
    - assets/images/student.png
    - assets/images/icon_excel.png
    - assets/images/icon_add.png
    - assets/images/material.png
    - assets/images/filter.png
    - assets/images/back.jpg
    - assets/images/mail.png
    - assets/images/lock.png
    - assets/images/mobile.png
    - assets/images/lecutre.png
    - assets/images/delete.png

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
    - family: video
      fonts:
        - asset: assets/fonts/icons/video.ttf
